use std::env;
use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

fn obfuscate(input: &str, key: u8) -> Vec<u8> {
    input
        .as_bytes()
        .iter()
        .enumerate()
        .map(|(i, b)| b ^ key.wrapping_add((i as u8).wrapping_mul(31)))
        .collect()
}

fn render_vec(bytes: &[u8]) -> String {
    if bytes.is_empty() {
        return "&[]".to_string();
    }
    let body = bytes
        .iter()
        .map(|b| b.to_string())
        .collect::<Vec<_>>()
        .join(", ");
    format!("&[{body}]")
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=AUTH_KEY");
    println!("cargo:rerun-if-env-changed=CONTROL_URL");

    let auth_key = env::var("AUTH_KEY").unwrap_or_default();
    let control_url = env::var("CONTROL_URL").unwrap_or_default();

    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0);
    let pid = std::process::id() as u64;
    let mixed = now ^ pid.rotate_left(13);
    let key = (mixed as u8).wrapping_add(0x5d);

    let auth_obf = obfuscate(&auth_key, key);
    let control_obf = obfuscate(&control_url, key);

    let generated = format!(
        "// AUTO-GENERATED BY build.rs. DO NOT EDIT.\n\
         pub const BUILD_KEY: u8 = {key};\n\
         pub const AUTH_KEY_OBF: &[u8] = {auth};\n\
         pub const CONTROL_URL_OBF: &[u8] = {control};\n\
         fn decode(bytes: &[u8]) -> Option<String> {{\n\
             if bytes.is_empty() {{\n\
                 return None;\n\
             }}\n\
             let mut out = Vec::with_capacity(bytes.len());\n\
             for (i, b) in bytes.iter().enumerate() {{\n\
                 out.push(b ^ BUILD_KEY.wrapping_add((i as u8).wrapping_mul(31)));\n\
             }}\n\
             String::from_utf8(out).ok()\n\
         }}\n\
         pub fn build_auth_key() -> Option<String> {{\n\
             decode(AUTH_KEY_OBF)\n\
         }}\n\
         pub fn build_control_url() -> Option<String> {{\n\
             decode(CONTROL_URL_OBF)\n\
         }}\n",
        key = key,
        auth = render_vec(&auth_obf),
        control = render_vec(&control_obf)
    );

    let out_file = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("src/secrets.rs");
    fs::write(out_file, generated).expect("failed to write src/secrets.rs");
}
