// AUTO-GENERATED BY build.rs. DO NOT EDIT.
pub const BUILD_KEY: u8 = 49;
pub const AUTH_KEY_OBF: &[u8] = &[];
pub const CONTROL_URL_OBF: &[u8] = &[];
fn decode(bytes: &[u8]) -> Option<String> {
    if bytes.is_empty() {
        return None;
    }
    let mut out = Vec::with_capacity(bytes.len());
    for (i, b) in bytes.iter().enumerate() {
        out.push(b ^ BUILD_KEY.wrapping_add((i as u8).wrapping_mul(31)));
    }
    String::from_utf8(out).ok()
}
pub fn build_auth_key() -> Option<String> {
    decode(AUTH_KEY_OBF)
}
pub fn build_control_url() -> Option<String> {
    decode(CONTROL_URL_OBF)
}
